'use client';
import { useState } from 'react';
import Link from 'next/link';
import { Header } from '@/components/dashboard/header';
import { Card, CardContent, CardDescription, CardHeader, CardTitle, CardFooter } from '@/components/ui/card';
import { BookOpen, Sprout, Landmark, Search, Lightbulb, Loader2, CheckCircle2, XCircle } from 'lucide-react';
import { Input } from '@/components/ui/input';
import { Button } from '@/components/ui/button';
import { SidebarTrigger } from '@/components/ui/sidebar';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { fetchQuizQuestion } from '@/app/actions';
import { useToast } from '@/hooks/use-toast';
import { cn } from '@/lib/utils';
import type { QuizQuestionOutput } from '@/ai/flows/quiz-flow';
import { useUser, useDoc, useFirestore } from '@/firebase';
import { doc } from 'firebase/firestore';
import { useMemoFirebase } from '@/firebase/provider';
import { OfflineGuide } from '@/components/dashboard/OfflineGuide';

const learningTopics = [
    {
        title: 'Modern Crop Management',
        description: 'Advanced techniques for improving crop yield and health.',
        icon: Sprout,
        href: 'https://www.youtube.com/results?search_query=modern+crop+management+for+indian+farmers',
    },
    {
        title: 'Soil Health & Nutrition',
        description: 'Understand the importance of soil health and how to maintain it.',
        icon: BookOpen,
        href: 'https://www.youtube.com/results?search_query=soil+health+and+nutrition+for+indian+farmers',
    },
    {
        title: 'Government Schemes & Subsidies',
        description: 'Information on the latest government schemes for farmers.',
        icon: Landmark,
        href: 'https://www.youtube.com/results?search_query=government+schemes+for+indian+farmers',
    },
    {
        title: 'Pest and Disease Control',
        description: 'Effective and sustainable methods to protect your crops.',
        icon: Sprout,
        href: 'https://www.youtube.com/results?search_query=pest+and+disease+control+for+indian+farmers',
    },
    {
        title: 'Water Management',
        description: 'Learn about efficient irrigation techniques to save water.',
        icon: BookOpen,
        href: 'https://www.youtube.com/results?search_query=water+management+for+indian+farmers',
    }
];

type UserProfile = {
  language?: string;
};

export default function LearnPage() {
  const [searchQuery, setSearchQuery] = useState('');
  const [quizTopic, setQuizTopic] = useState(learningTopics[0].title);
  const [isLoading, setIsLoading] = useState(false);
  const [quizData, setQuizData] = useState<QuizQuestionOutput | null>(null);
  const [selectedAnswer, setSelectedAnswer] = useState<string | null>(null);
  const { toast } = useToast();
  const { user } = useUser();
  const firestore = useFirestore();

  const userProfileRef = useMemoFirebase(() => {
    if (!firestore || !user) return null;
    return doc(firestore, 'userProfile', user.uid);
  }, [firestore, user]);

  const { data: userProfile } = useDoc<UserProfile>(userProfileRef);

  const handleSearch = (e: React.FormEvent) => {
    e.preventDefault();
    if (!searchQuery.trim()) return;
    const youtubeSearchUrl = `https://www.youtube.com/results?search_query=${encodeURIComponent(searchQuery)}`;
    window.open(youtubeSearchUrl, '_blank');
  };

  const startQuiz = async () => {
    setIsLoading(true);
    setQuizData(null);
    setSelectedAnswer(null);
    const result = await fetchQuizQuestion({ 
      topic: quizTopic,
      language: userProfile?.language || 'English',
    });
    if (result.error) {
      toast({
        variant: 'destructive',
        title: 'Error',
        description: 'Failed to generate quiz question. Please try again.',
      });
    } else {
      setQuizData(result.data);
    }
    setIsLoading(false);
  };
  
  const handleAnswerSelection = (answer: string) => {
    if (selectedAnswer) return; // Prevent changing answer
    setSelectedAnswer(answer);
  };

  return (
    <div className="flex flex-col min-h-screen">
      <Header rightContent={<SidebarTrigger />} />
      <main className="flex-1 p-4">
        <div className="mx-auto max-w-7xl space-y-6">
          
          <OfflineGuide />

          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2"><Lightbulb className="text-primary"/>AI-Powered Quiz</CardTitle>
              <CardDescription>Test your farming knowledge with a quick question generated by AI.</CardDescription>
            </CardHeader>
            <CardContent>
              {!quizData && !isLoading && (
                <div className="flex sm:flex-row flex-col gap-2">
                   <Select value={quizTopic} onValueChange={setQuizTopic}>
                    <SelectTrigger>
                      <SelectValue placeholder="Select a topic" />
                    </SelectTrigger>
                    <SelectContent>
                      {learningTopics.map((topic, index) => (
                        <SelectItem key={index} value={topic.title}>{topic.title}</SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                  <Button onClick={startQuiz} className="w-full sm:w-auto">Start Quiz</Button>
                </div>
              )}

              {isLoading && (
                <div className="flex flex-col items-center justify-center text-center p-4 rounded-lg bg-card border h-48">
                    <Loader2 className="h-8 w-8 animate-spin text-primary mb-2" />
                    <p className="font-semibold">Generating your question...</p>
                </div>
              )}

              {quizData && (
                <div className="space-y-4">
                  <p className="font-semibold">{quizData.question}</p>
                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
                    {quizData.options.map((option, index) => {
                      const isSelected = selectedAnswer === option;
                      const isCorrect = quizData.correctAnswer === option;
                      return (
                        <Button
                          key={index}
                          variant="outline"
                          className={cn(
                            "h-auto py-2 justify-start text-left whitespace-normal",
                            isSelected && isCorrect && "bg-green-500/20 border-green-500 hover:bg-green-500/30",
                            isSelected && !isCorrect && "bg-red-500/20 border-red-500 hover:bg-red-500/30",
                          )}
                          onClick={() => handleAnswerSelection(option)}
                          disabled={!!selectedAnswer}
                        >
                          <div className="flex items-center gap-2">
                              {isSelected ? (isCorrect ? <CheckCircle2 className="text-green-500" /> : <XCircle className="text-red-500"/>) : <div className="w-5 h-5"/>}
                            <span>{option}</span>
                          </div>
                        </Button>
                      )
                    })}
                  </div>
                  {selectedAnswer && (
                    <div className="p-4 rounded-md bg-secondary/50 border animate-in fade-in-50">
                      <h4 className="font-semibold text-primary">Explanation</h4>
                      <p className="text-sm text-muted-foreground">{quizData.explanation}</p>
                    </div>
                  )}
                </div>
              )}
            </CardContent>
            {quizData && (
                <CardFooter>
                    <Button onClick={startQuiz} disabled={isLoading} className="w-full">
                        {isLoading ? <Loader2 className="h-4 w-4 animate-spin"/> : 'Next Question'}
                    </Button>
                </CardFooter>
            )}
          </Card>
          
          <div>
            <h2 className="text-xl font-semibold mb-4">Learning Center</h2>
            <form onSubmit={handleSearch} className="flex gap-2 mb-6">
              <Input
                value={searchQuery}
                onChange={e => setSearchQuery(e.target.value)}
                placeholder="Search for farming videos on YouTube..."
                className="flex-1"
              />
              <Button type="submit">
                <Search className="w-4 h-4" />
              </Button>
            </form>

            <h3 className="text-lg font-semibold mb-4">Popular Topics</h3>
            <div className="grid gap-4 sm:grid-cols-1 md:grid-cols-2 lg:grid-cols-3">
              {learningTopics.map((topic, index) => (
                  <Link href={topic.href} key={index} target="_blank" rel="noopener noreferrer">
                      <Card className="h-full hover:bg-muted/50 transition-colors">
                          <CardHeader className="flex flex-row items-center gap-4">
                              <div className="bg-primary/20 p-2 rounded-lg">
                                  <topic.icon className="w-6 h-6 text-primary" />
                              </div>
                              <CardTitle className="text-lg">{topic.title}</CardTitle>
                          </CardHeader>
                          <CardContent>
                              <CardDescription>{topic.description}</CardDescription>
                          </CardContent>
                      </Card>
                  </Link>
              ))}
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}
